---
name: "Test Add On"
description: "My first real add-on!"
version: "1.0.0"
slug: "test_add_on"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
   
options:
  active_appliances: null
  
schema:
  active_appliances: str
  
  
